# Set false path for the user reset generated by CMAC
set_false_path -through [get_nets /cmac_inst/usr_rx_reset]
set_false_path -through [get_nets /cmac_inst/usr_tx_reset]
# Set false path for upper design derived reset
set_false_path -through [get_pins /cmac_sys_reset]

# Set CDC inter clock delay, assuming AXI-Stream Max Freq at 300MHz
set axi_clk [get_clocks -of_object [get_nets /ap_clk]]
set cmac_clk_rx [get_clocks -of_object [get_nets /cmac_clk_rx]]
set cmac_clk_tx [get_clocks -of_object [get_nets /cmac_clk_tx]]
set_max_delay -datapath_only -from $axi_clk -to $cmac_clk_rx 3.333
set_max_delay -datapath_only -from $axi_clk -to $cmac_clk_tx 3.333
set_max_delay -datapath_only -from $cmac_clk_rx -to $axi_clk 3.103
set_max_delay -datapath_only -from $cmac_clk_tx -to $axi_clk 3.103
